<?php

namespace Database\Seeders;

use App\Models\Division;
use App\Models\Subdivision;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DivisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $divisions = [
            [
                'country_id' => 1,
                'name' => 'Guatemala',
                'is_capital' => true,
                'subdivisions' => [
                    ['name' => 'Guatemala', 'is_capital' => true],
                    ['name' => 'San José del Golfo', 'is_capital' => false],
                    ['name' => 'Chinautla', 'is_capital' => false],
                    ['name' => 'San Pedro Ayampuc', 'is_capital' => false],
                    ['name' => 'San Pedro Sacatepéquez', 'is_capital' => false],
                    ['name' => 'Chuarrancho', 'is_capital' => false],
                    ['name' => 'Fraijanes', 'is_capital' => false],
                    ['name' => 'Amatitlán', 'is_capital' => false],
                    ['name' => 'Villa Nueva', 'is_capital' => false],
                    ['name' => 'Villa Canales', 'is_capital' => false],
                    ['name' => 'Petapa', 'is_capital' => false],
                    ['name' => 'Santa Catarina Pinula', 'is_capital' => false],
                    ['name' => 'San José Pinula', 'is_capital' => false],
                    ['name' => 'Palencia', 'is_capital' => false],
                    ['name' => 'Mixco', 'is_capital' => false],
                    ['name' => 'San Raymundo', 'is_capital' => false],
                    ['name' => 'San Juan Sacatepéquez', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'El Progreso',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Guastatoya', 'is_capital' => true],
                    ['name' => 'Morazán', 'is_capital' => false],
                    ['name' => 'San Agustín Acasaguastlán', 'is_capital' => false],
                    ['name' => 'Sansare', 'is_capital' => false],
                    ['name' => 'Sanarate', 'is_capital' => false],
                    ['name' => 'San Antonio La Paz', 'is_capital' => false],
                    ['name' => 'San Cristobal Acasaguastlán', 'is_capital' => false],
                    ['name' => 'El Jícaro', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Sacatepéquez',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Antigua Guatemala', 'is_capital' => true],
                    ['name' => 'Jocotenango', 'is_capital' => false],
                    ['name' => 'Pastores', 'is_capital' => false],
                    ['name' => 'Sumpango', 'is_capital' => false],
                    ['name' => 'Santo Domingo Xenacoj', 'is_capital' => false],
                    ['name' => 'Santiago Sacatepéquez', 'is_capital' => false],
                    ['name' => 'San Bartolomé Milpas Altas', 'is_capital' => false],
                    ['name' => 'San Lucas Sacatepéquez', 'is_capital' => false],
                    ['name' => 'Santa Lucia Milpas Altas', 'is_capital' => false],
                    ['name' => 'Magdalena Milpas Altas', 'is_capital' => false],
                    ['name' => 'Santa María de Jesus', 'is_capital' => false],
                    ['name' => 'Ciudad Vieja', 'is_capital' => false],
                    ['name' => 'San Miguel Dueñas', 'is_capital' => false],
                    ['name' => 'Alotenango', 'is_capital' => false],
                    ['name' => 'San Antonio Aguas Calientes', 'is_capital' => false],
                    ['name' => 'Santa Catalina Barahona', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Chimaltenango',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Chimaltenango', 'is_capital' => true],
                    ['name' => 'San José Poaquil', 'is_capital' => false],
                    ['name' => 'San MartÍn Jilotepeque', 'is_capital' => false],
                    ['name' => 'Comalapa', 'is_capital' => false],
                    ['name' => 'Santa Apolonia', 'is_capital' => false],
                    ['name' => 'Tecpan Guatemala', 'is_capital' => false],
                    ['name' => 'Patzun', 'is_capital' => false],
                    ['name' => 'Pochuta', 'is_capital' => false],
                    ['name' => 'Patzicía', 'is_capital' => false],
                    ['name' => 'Santa Cruz Balanya', 'is_capital' => false],
                    ['name' => 'Acatenango', 'is_capital' => false],
                    ['name' => 'Yepocapa', 'is_capital' => false],
                    ['name' => 'San Andrés Itzapa', 'is_capital' => false],
                    ['name' => 'Parramos', 'is_capital' => false],
                    ['name' => 'Zaragoza', 'is_capital' => false],
                    ['name' => 'El Tejar', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Escuintla',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Escuintla', 'is_capital' => true],
                    ['name' => 'Santa Lucía Cotzumalguapa', 'is_capital' => false],
                    ['name' => 'La Democracia', 'is_capital' => false],
                    ['name' => 'Siquinala', 'is_capital' => false],
                    ['name' => 'Masagua', 'is_capital' => false],
                    ['name' => 'Tiquisate', 'is_capital' => false],
                    ['name' => 'La Gomera', 'is_capital' => false],
                    ['name' => 'Guanagazapa', 'is_capital' => false],
                    ['name' => 'San José', 'is_capital' => false],
                    ['name' => 'Iztapa', 'is_capital' => false],
                    ['name' => 'Palín', 'is_capital' => false],
                    ['name' => 'San Vicente Pacaya', 'is_capital' => false],
                    ['name' => 'Nueva Concepción', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Santa Rosa',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Cuilapa', 'is_capital' => true],
                    ['name' => 'Barberena', 'is_capital' => false],
                    ['name' => 'Santa Rosa De Lima', 'is_capital' => false],
                    ['name' => 'Casillas', 'is_capital' => false],
                    ['name' => 'San Rafael Las Flores', 'is_capital' => false],
                    ['name' => 'Oratorio', 'is_capital' => false],
                    ['name' => 'San Juan Tecuaco', 'is_capital' => false],
                    ['name' => 'Chiquimulilla', 'is_capital' => false],
                    ['name' => 'Taxisco', 'is_capital' => false],
                    ['name' => 'Santa María Ixhuatan', 'is_capital' => false],
                    ['name' => 'Guazacapan', 'is_capital' => false],
                    ['name' => 'Santa Cruz Naranjo', 'is_capital' => false],
                    ['name' => 'Pueblo Nuevo Viñas', 'is_capital' => false],
                    ['name' => 'Nueva Santa Rosa', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Sololá',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Sololá', 'is_capital' => true],
                    ['name' => 'San José Chacayá', 'is_capital' => false],
                    ['name' => 'Santa María Visitación', 'is_capital' => false],
                    ['name' => 'Santa Lucía Utatlan', 'is_capital' => false],
                    ['name' => 'Nahuala', 'is_capital' => false],
                    ['name' => 'Santa Catarina Ixtahuacan', 'is_capital' => false],
                    ['name' => 'Santa Clara La Laguna', 'is_capital' => false],
                    ['name' => 'Concepción', 'is_capital' => false],
                    ['name' => 'San Andrés Semetabaj', 'is_capital' => false],
                    ['name' => 'Panajachel', 'is_capital' => false],
                    ['name' => 'Santa Catarina Palopó', 'is_capital' => false],
                    ['name' => 'San Antonio Palopó', 'is_capital' => false],
                    ['name' => 'San Lucas Tolimán', 'is_capital' => false],
                    ['name' => 'Santa Cruz La Laguna', 'is_capital' => false],
                    ['name' => 'San Pablo La Laguna', 'is_capital' => false],
                    ['name' => 'San Marcos La Laguna', 'is_capital' => false],
                    ['name' => 'San Juan La Laguna', 'is_capital' => false],
                    ['name' => 'San Pedro La Laguna', 'is_capital' => false],
                    ['name' => 'Santiago Atitlán', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Totonicapan',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Totonicapán', 'is_capital' => true],
                    ['name' => 'San Cristóbal Totonicapan', 'is_capital' => false],
                    ['name' => 'San Francisco El Alto', 'is_capital' => false],
                    ['name' => 'San Andrés Xecul', 'is_capital' => false],
                    ['name' => 'Momostenango', 'is_capital' => false],
                    ['name' => 'Santa María Chiquimula', 'is_capital' => false],
                    ['name' => 'Santa Lucía La Reforma', 'is_capital' => false],
                    ['name' => 'San Bartolo', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Quetzaltenango',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Quetzaltenango', 'is_capital' => true],
                    ['name' => 'Salcajá', 'is_capital' => false],
                    ['name' => 'Olintepeque', 'is_capital' => false],
                    ['name' => 'San Carlos Sija', 'is_capital' => false],
                    ['name' => 'Sibilia', 'is_capital' => false],
                    ['name' => 'Cabricán', 'is_capital' => false],
                    ['name' => 'Cajolá', 'is_capital' => false],
                    ['name' => 'San Miguel Siguilá', 'is_capital' => false],
                    ['name' => 'Ostuncalco', 'is_capital' => false],
                    ['name' => 'San Mateo', 'is_capital' => false],
                    ['name' => 'Concepción Chiquirichapa', 'is_capital' => false],
                    ['name' => 'San Martín Sacatepéquez', 'is_capital' => false],
                    ['name' => 'Almolonga', 'is_capital' => false],
                    ['name' => 'Cantel', 'is_capital' => false],
                    ['name' => 'Huitán', 'is_capital' => false],
                    ['name' => 'Zunil', 'is_capital' => false],
                    ['name' => 'Colomba', 'is_capital' => false],
                    ['name' => 'San Francisco La Unión', 'is_capital' => false],
                    ['name' => 'El Palmar', 'is_capital' => false],
                    ['name' => 'Coatepeque', 'is_capital' => false],
                    ['name' => 'Génova', 'is_capital' => false],
                    ['name' => 'Flores Costa Cuca', 'is_capital' => false],
                    ['name' => 'La Esperanza', 'is_capital' => false],
                    ['name' => 'Palestina de Los Altos', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Suchitepéquez',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Mazatenango', 'is_capital' => true],
                    ['name' => 'Cuyotenango', 'is_capital' => false],
                    ['name' => 'San Francisco Zapotitlán', 'is_capital' => false],
                    ['name' => 'San Bernardino', 'is_capital' => false],
                    ['name' => 'San José El Idolo', 'is_capital' => false],
                    ['name' => 'Santo Domingo Suchitepéquez', 'is_capital' => false],
                    ['name' => 'San Lorenzo', 'is_capital' => false],
                    ['name' => 'Samayac', 'is_capital' => false],
                    ['name' => 'San Pablo Jocopilas', 'is_capital' => false],
                    ['name' => 'San Antonio Suchitepéquez', 'is_capital' => false],
                    ['name' => 'San Miguel Panán', 'is_capital' => false],
                    ['name' => 'San Gabriel', 'is_capital' => false],
                    ['name' => 'Chicacao', 'is_capital' => false],
                    ['name' => 'Patulul', 'is_capital' => false],
                    ['name' => 'Santa Barbara', 'is_capital' => false],
                    ['name' => 'San Juan Bautista', 'is_capital' => false],
                    ['name' => 'Santo Tomßs La Unión', 'is_capital' => false],
                    ['name' => 'Zunilito', 'is_capital' => false],
                    ['name' => 'Pueblo Nuevo', 'is_capital' => false],
                    ['name' => 'Río Bravo', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Retalhuleu',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Retalhuleu', 'is_capital' => true],
                    ['name' => 'San Sebastián', 'is_capital' => false],
                    ['name' => 'Santa Cruz Muluá', 'is_capital' => false],
                    ['name' => 'San Martín Zapotitlán', 'is_capital' => false],
                    ['name' => 'San Felipe', 'is_capital' => false],
                    ['name' => 'San Andrés Villa Seca', 'is_capital' => false],
                    ['name' => 'Champerico', 'is_capital' => false],
                    ['name' => 'Nuevo San Carlos', 'is_capital' => false],
                    ['name' => 'El Asintal', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'San Marcos',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'San Marcos', 'is_capital' => true],
                    ['name' => 'Ayutla', 'is_capital' => false],
                    ['name' => 'Catarina', 'is_capital' => false],
                    ['name' => 'Comitancillo', 'is_capital' => false],
                    ['name' => 'Concepción Tutuapa', 'is_capital' => false],
                    ['name' => 'El Quetzal', 'is_capital' => false],
                    ['name' => 'El Rodeo', 'is_capital' => false],
                    ['name' => 'El Tumblador', 'is_capital' => false],
                    ['name' => 'Ixchiguán', 'is_capital' => false],
                    ['name' => 'La Reforma', 'is_capital' => false],
                    ['name' => 'Malacatán', 'is_capital' => false],
                    ['name' => 'Nuevo Progreso', 'is_capital' => false],
                    ['name' => 'Ocós', 'is_capital' => false],
                    ['name' => 'Pajapita', 'is_capital' => false],
                    ['name' => 'Esquipulas Palo Gordo', 'is_capital' => false],
                    ['name' => 'San Antonio Sacatepéquez', 'is_capital' => false],
                    ['name' => 'San Cristóbal Cucho', 'is_capital' => false],
                    ['name' => 'San José Ojetenam', 'is_capital' => false],
                    ['name' => 'San Lorenzo', 'is_capital' => false],
                    ['name' => 'San Miguel Ixtahuacán', 'is_capital' => false],
                    ['name' => 'San Pablo', 'is_capital' => false],
                    ['name' => 'San Pedro Sacatepéquez', 'is_capital' => false],
                    ['name' => 'San Rafael Pie de la Cuesta', 'is_capital' => false],
                    ['name' => 'Sibinal', 'is_capital' => false],
                    ['name' => 'Sipacapa', 'is_capital' => false],
                    ['name' => 'Tacaná', 'is_capital' => false],
                    ['name' => 'Tajumulco', 'is_capital' => false],
                    ['name' => 'Tejutla', 'is_capital' => false],
                    ['name' => 'Río Blanco', 'is_capital' => false],
                    ['name' => 'La Blanca', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Huehuetenango',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Huehuetenango', 'is_capital' => true],
                    ['name' => 'Chiantla', 'is_capital' => false],
                    ['name' => 'Malacatancito', 'is_capital' => false],
                    ['name' => 'Cuilco', 'is_capital' => false],
                    ['name' => 'Nentón', 'is_capital' => false],
                    ['name' => 'San Pedro Necta', 'is_capital' => false],
                    ['name' => 'Jacaltenango', 'is_capital' => false],
                    ['name' => 'Soloma', 'is_capital' => false],
                    ['name' => 'Ixtahuacán', 'is_capital' => false],
                    ['name' => 'Santa Bárbara', 'is_capital' => false],
                    ['name' => 'La Libertad', 'is_capital' => false],
                    ['name' => 'La Democracia', 'is_capital' => false],
                    ['name' => 'San Miguel Acatán', 'is_capital' => false],
                    ['name' => 'San Rafael La Independencia', 'is_capital' => false],
                    ['name' => 'Todos Santos Cuchumatánes', 'is_capital' => false],
                    ['name' => 'San Juan Atitán', 'is_capital' => false],
                    ['name' => 'Santa Eulalia', 'is_capital' => false],
                    ['name' => 'San Mateo Ixtatán', 'is_capital' => false],
                    ['name' => 'Colotenango', 'is_capital' => false],
                    ['name' => 'San Sebastián Huehetenango', 'is_capital' => false],
                    ['name' => 'Tectitán', 'is_capital' => false],
                    ['name' => 'Concepción Huista', 'is_capital' => false],
                    ['name' => 'San Juan Ixcoy', 'is_capital' => false],
                    ['name' => 'San Antonio Huista', 'is_capital' => false],
                    ['name' => 'San Sebastián Coatán', 'is_capital' => false],
                    ['name' => 'Barillas', 'is_capital' => false],
                    ['name' => 'Aguacatán', 'is_capital' => false],
                    ['name' => 'San Rafael Petzal', 'is_capital' => false],
                    ['name' => 'San Gaspar Ixchil', 'is_capital' => false],
                    ['name' => 'Santiago Chimaltenango', 'is_capital' => false],
                    ['name' => 'Santa Ana Huista', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'El Quiché',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Santa Cruz del Quiché', 'is_capital' => true],
                    ['name' => 'Chiché', 'is_capital' => false],
                    ['name' => 'Chinique', 'is_capital' => false],
                    ['name' => 'Zacualpa', 'is_capital' => false],
                    ['name' => 'Chajul', 'is_capital' => false],
                    ['name' => 'Chichicastenango', 'is_capital' => false],
                    ['name' => 'Patzité', 'is_capital' => false],
                    ['name' => 'San Antonio Ilotenango', 'is_capital' => false],
                    ['name' => 'San Pedro Jocopilas', 'is_capital' => false],
                    ['name' => 'Cunén', 'is_capital' => false],
                    ['name' => 'San Juan Cotzal', 'is_capital' => false],
                    ['name' => 'Joyabaj', 'is_capital' => false],
                    ['name' => 'Nebaj', 'is_capital' => false],
                    ['name' => 'San Andrés Sajcabajá', 'is_capital' => false],
                    ['name' => 'Uspantán', 'is_capital' => false],
                    ['name' => 'Sacapulas', 'is_capital' => false],
                    ['name' => 'San Bartolomé Jocotenango', 'is_capital' => false],
                    ['name' => 'Canillá', 'is_capital' => false],
                    ['name' => 'Chicamán', 'is_capital' => false],
                    ['name' => 'Ixcán', 'is_capital' => false],
                    ['name' => 'Pachalum', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Baja Verapaz',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Salamá', 'is_capital' => true],
                    ['name' => 'San Miguel Chicaj', 'is_capital' => false],
                    ['name' => 'Rabinal', 'is_capital' => false],
                    ['name' => 'Cubulco', 'is_capital' => false],
                    ['name' => 'Granados', 'is_capital' => false],
                    ['name' => 'El Chol', 'is_capital' => false],
                    ['name' => 'San Jerónimo', 'is_capital' => false],
                    ['name' => 'Purulhá', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Alta Verapaz',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Cobán', 'is_capital' => true],
                    ['name' => 'Santa Cruz Verapaz', 'is_capital' => false],
                    ['name' => 'San Cristóbal Verapaz', 'is_capital' => false],
                    ['name' => 'Tactic', 'is_capital' => false],
                    ['name' => 'Tamahù', 'is_capital' => false],
                    ['name' => 'Tucurú', 'is_capital' => false],
                    ['name' => 'Panzós', 'is_capital' => false],
                    ['name' => 'Senahú', 'is_capital' => false],
                    ['name' => 'San Pedro Carchá', 'is_capital' => false],
                    ['name' => 'San Juan Chamelco', 'is_capital' => false],
                    ['name' => 'Lanquín', 'is_capital' => false],
                    ['name' => 'Cahabón', 'is_capital' => false],
                    ['name' => 'Chisec', 'is_capital' => false],
                    ['name' => 'Chahal', 'is_capital' => false],
                    ['name' => 'Fray Bartolomé de Las Casas', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Petén',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Flores', 'is_capital' => true],
                    ['name' => 'San José', 'is_capital' => false],
                    ['name' => 'San Benito', 'is_capital' => false],
                    ['name' => 'San Andrés', 'is_capital' => false],
                    ['name' => 'La Libertad', 'is_capital' => false],
                    ['name' => 'San Francisco', 'is_capital' => false],
                    ['name' => 'Santa Ana', 'is_capital' => false],
                    ['name' => 'Dolores', 'is_capital' => false],
                    ['name' => 'San Luis', 'is_capital' => false],
                    ['name' => 'Sayaxché', 'is_capital' => false],
                    ['name' => 'Melchor De Mencos', 'is_capital' => false],
                    ['name' => 'Poptún', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Izabal',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Puerto Barrios', 'is_capital' => true],
                    ['name' => 'Lívingston', 'is_capital' => false],
                    ['name' => 'El Estor', 'is_capital' => false],
                    ['name' => 'Morales', 'is_capital' => false],
                    ['name' => 'Los Amates', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Zacapa',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Cabañas', 'is_capital' => true],
                    ['name' => 'Estanzuela', 'is_capital' => false],
                    ['name' => 'Gualán', 'is_capital' => false],
                    ['name' => 'Huité', 'is_capital' => false],
                    ['name' => 'La Unión', 'is_capital' => false],
                    ['name' => 'Río Hondo', 'is_capital' => false],
                    ['name' => 'San Jorge', 'is_capital' => false],
                    ['name' => 'San Diego', 'is_capital' => false],
                    ['name' => 'Teculután', 'is_capital' => false],
                    ['name' => 'Usumatlán', 'is_capital' => false],
                    ['name' => 'Zacapa', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Chiquimula',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Chiquimula', 'is_capital' => true],
                    ['name' => 'San José La Arada', 'is_capital' => false],
                    ['name' => 'San Juan Ermita', 'is_capital' => false],
                    ['name' => 'Jocotán', 'is_capital' => false],
                    ['name' => 'Camotán', 'is_capital' => false],
                    ['name' => 'Olopa', 'is_capital' => false],
                    ['name' => 'Esquipulas', 'is_capital' => false],
                    ['name' => 'Concepción Las Minas', 'is_capital' => false],
                    ['name' => 'Quetzaltepeque', 'is_capital' => false],
                    ['name' => 'San Jacinto', 'is_capital' => false],
                    ['name' => 'Ipala', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Jalapa',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Jalapa', 'is_capital' => true],
                    ['name' => 'San Pedro Pinula', 'is_capital' => false],
                    ['name' => 'San Luis Jilotepeque', 'is_capital' => false],
                    ['name' => 'San Manuel Chaparrón', 'is_capital' => false],
                    ['name' => 'San Carlos Alzatate', 'is_capital' => false],
                    ['name' => 'Monjas', 'is_capital' => false],
                    ['name' => 'Mataquescuintla', 'is_capital' => false],
                ],
            ],
            [
                'country_id' => 1,
                'name' => 'Jutiapa',
                'is_capital' => false,
                'subdivisions' => [
                    ['name' => 'Jutiapa', 'is_capital' => true],
                    ['name' => 'El Progreso', 'is_capital' => false],
                    ['name' => 'Santa Catarina Mita', 'is_capital' => false],
                    ['name' => 'Agua Blanca', 'is_capital' => false],
                    ['name' => 'Asunción Mita', 'is_capital' => false],
                    ['name' => 'Yupiltepeque', 'is_capital' => false],
                    ['name' => 'Atescatempa', 'is_capital' => false],
                    ['name' => 'Jerez', 'is_capital' => false],
                    ['name' => 'El Adelanto', 'is_capital' => false],
                    ['name' => 'Zapotitlán', 'is_capital' => false],
                    ['name' => 'Comapa', 'is_capital' => false],
                    ['name' => 'Jalpatagua', 'is_capital' => false],
                    ['name' => 'Conguaco', 'is_capital' => false],
                    ['name' => 'Moyuta', 'is_capital' => false],
                    ['name' => 'Pasaco', 'is_capital' => false],
                    ['name' => 'San José Acatempa', 'is_capital' => false],
                    ['name' => 'Quesada', 'is_capital' => false],
                ],
            ],
        ];

        foreach ($divisions as $division) {
            $subdvisions = $division['subdivisions'];
            unset($division['subdivisions']);

            $division = Division::create($division);

            foreach($subdvisions as $subdivision) {
                $subdivision['division_id'] = $division->id;
                Subdivision::create($subdivision);
            }
        }
    }
}
